---
title: "Scraping for an impactful Civil Service career"
author: "Tobias Jolly - Cabinet Office"
date: " April 2020"
output: 
  ioslides_presentation:
    logo: images/HIPE_logo.png
---

<style>
pre {
  font-size: 120px;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Outline


- Outline
- HIPE
- The data
- The code
- Questions


## What is HIPE?

<div class="centered"><font size=10>HIPE’s mission:</font></div>
\b
<div class="centered"><font size="50">"To helps civil servants do the most good they can, in government and beyond!"</font></div>

## The data

"https://www.civilservicejobs.service.gov.uk"

## The code

```{r include=FALSE}
devtools::document()

```


```{r echo = TRUE}
my_session = CivilServiceR::login('user_name_and_password.R')
rm(password)


search_url = "https://www.civilservicejobs.service.gov.uk/csr/index.cgi?SID=YWdlbnRfY29kZT0xNjU5NTc5JmNzb3VyY2U9Y3NhbGVydHNlYXJjaCZ1c2Vyc2VhcmNoY29udGV4dD0mb3duZXJ0eXBlPWZhaXImc3RvcmVzZWFyY2hjb250ZXh0PTEmcGFnZWFjdGlvbj1zZWFyY2hieWFnZW50Y29kZSZwYWdlY2xhc3M9Sm9icyZvd25lcj01MDcwMDAwJnJlcXNpZz0xNTgzMzE3ODg3LTZlOTlmNzg1MGIyZmZmNWQ5NmRjMGMzYmU1MGY2NTY3MWIxZTE4MzQ="

search_pages <- CivilServiceR::get_all_search_pages(my_session, search_url)

scraped_page <- CivilServiceR::scrape_search_page(my_session, search_pages[1])

new_advert_count <- 1
i <- 1
job_url <- scraped_page$link[1]

full_job_data <- CivilServiceR::scrape_full_job(job_url, i, my_session, new_advert_count)


```

